# https://github.com/DoranekoSystems/frida-ceserver/wiki/Config
[general]
target =  ""
targetOS = "ios"
mode =  "attach"
arch = 3
ceversion =  "7.4.2"

[ipconfig]
frida_server_ip =  ""
native_ceserver_ip =  ""
debugserver_ip =  ""
  
[ssh_auto]
enable = false
ip = ""
username = ""
password = ""
ceserver_path =""
debugserver_path = ""

[adb_auto]
enable = false
frida_server_path = ""
ceserver_path = ""
gdbserver_path = ""

[extended_function]
fix_module_size =  false
manualParser = false
javaDissect  = false
custom_symbol_loader =  ""